### ISSUE TITLE
您好，启动之后无法检测，报错：Uncaught (in promise) Error: Failed to compile fragment shader.

### ISSUE THREAD

**Issue by Erikfather** [zqingr/tfjs-yolov3-demo#1]
错误如下：
Uncaught (in promise) Error: Failed to compile fragment shader.
    at createFragmentShader (tfjs:2)
    at e.createProgram (tfjs:2)
    at compileProgram (tfjs:2)
    at tfjs:2
    at e.getAndSaveBinary (tfjs:2)
    at e.compileAndRun (tfjs:2)
    at e.maxPool (tfjs:2)
    at ENV.engine.runKernel.x (tf-core.esm.js:234)
    at tfjs:2
    at e.scopedRun (tfjs:2)
请问这是什么原因呢》谢谢

**Comment by zqingr** [comment]
你是启动的时候npm报错吗？ 这个是tfjs-yolov3的展示网页项目，不是tfjs-yolov3的项目，tfjs-yolov3的项目可查看[https://github.com/zqingr/tfjs-yolov3](https://github.com/zqingr/tfjs-yolov3)

**Comment by Erikfather** [comment]
> 你是启动的时候npm报错吗？ 这个是tfjs-yolov3的展示网页项目，不是tfjs-yolov3的项目，tfjs-yolov3的项目可查看https://github.com/zqingr/tfjs-yolov3
就是在网页里面打开之后，模型加载完没有检测结果。我们可以加个微信或者qq好友吗，想向您请教一下，可以吗

**Comment by Erikfather** [comment]
index.html文件中重复加载了tensorflow/tfjs文件，导致webgl和cpu后端被占有，无法编译片段着色器，需要将index.html文件中的<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs"></script>删除

**Comment by zqingr** [comment]
ok，谢谢。 貌似我在webpack的配置里把不加入tfjs的配置去掉了。
